# Generated by Django 4.2.7 on 2023-12-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=6255)),
                ('password_is_hashed', models.BooleanField(default=False)),
                ('isAdvisor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=6255)),
                ('password_is_hashed', models.BooleanField(default=False)),
            ],
        ),
    ]
