# Generated by Django 4.2.7 on 2023-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollNumber',
            field=models.CharField(max_length=15),
            preserve_default=False,
        ),
    ]
