# Generated by Django 4.2.7 on 2023-11-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
