# Generated by Django 4.2.7 on 2023-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_student_rollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollNumber',
            field=models.CharField(max_length=8),
        ),
    ]
