# Generated by Django 4.2.7 on 2023-11-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_remove_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
