# Generated by Django 4.2.7 on 2023-12-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_student_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registerNumber',
            field=models.CharField(max_length=15),
            preserve_default=False,
        ),
    ]
