# Generated by Django 5.0 on 2023-12-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_alter_student_name_alter_student_registernumber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['username']},
        ),
    ]
