# Generated by Django 4.2.7 on 2023-11-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_alter_staff_options_alter_staff_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelManagers(
            name='staff',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='staff',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='sasikalacse@siet.ac.in', max_length=255),
            preserve_default=False,
        ),
    ]
