# Generated by Django 4.2.7 on 2023-11-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_alter_staff_options_alter_staff_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='sasikalamam', max_length=6255),
            preserve_default=False,
        ),
    ]
