# Generated by Django 5.0 on 2024-01-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='lectureHall',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
