# Generated by Django 4.2.7 on 2023-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password_is_hashed',
            field=models.BooleanField(default=False),
        ),
    ]
