# Generated by Django 4.2.7 on 2023-11-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_staff_password_is_hashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=6255)),
                ('password_is_hashed', models.BooleanField(default=False)),
            ],
        ),
    ]
