# Generated by Django 4.2.7 on 2023-11-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='isAdvisor',
            field=models.BooleanField(default=False),
        ),
    ]
