# Generated by Django 4.2.7 on 2023-11-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_staff_isadvisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password_is_hashed',
            field=models.BooleanField(),
        ),
    ]
