# Generated by Django 5.0 on 2024-02-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_staff_userdob_staff_usermobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='images/profiles'),
        ),
    ]
