# Generated by Django 4.2.7 on 2023-11-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_alter_staff_password_is_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='isAdvisor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password_is_hashed',
            field=models.BooleanField(default=False),
        ),
    ]
