# Generated by Django 4.2.7 on 2023-11-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_alter_staff_isadvisor_alter_staff_password_is_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='isAdvisor',
            field=models.CharField(default='true', max_length=10),
        ),
    ]
