# Generated by Django 5.0 on 2023-12-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0001_initial'),
        ('auth_api', '0005_alter_student_name_alter_student_registernumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attadence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_api.student')),
            ],
        ),
    ]
