# Generated by Django 5.0 on 2023-12-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0002_attadence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attadence',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
