# Generated by Django 5.0 on 2023-12-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0004_rename_attadence_lecturehallattadence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturehallattadence',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendanceManager.lecturehall'),
        ),
    ]
