# Generated by Django 5.0 on 2023-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0005_alter_lecturehallattadence_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturehallattadence',
            name='isPresent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturehallattadence',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
