# Generated by Django 5.0 on 2023-12-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0007_alter_lecturehallattadence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturehallattadence',
            name='date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
