# Generated by Django 5.0 on 2023-12-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0008_alter_lecturehallattadence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturehallattadence',
            name='user',
        ),
        migrations.AddField(
            model_name='lecturehallattadence',
            name='user',
            field=models.ManyToManyField(to='attendanceManager.lecturehall'),
        ),
    ]
