# Generated by Django 5.0 on 2023-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0011_periods_remove_lecturehallattadence_ispresent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturehallattadence',
            name='date',
        ),
        migrations.AddField(
            model_name='classsession',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
