# Generated by Django 5.0 on 2023-12-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0012_remove_lecturehallattadence_date_classsession_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturehallattadence',
            name='classSession',
            field=models.ManyToManyField(to='attendanceManager.classsession'),
        ),
    ]
