# Generated by Django 5.0 on 2023-12-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0016_lecturehallattadence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturehallattadence',
            name='h5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
