# Generated by Django 5.0 on 2023-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0017_lecturehallattadence_h5'),
        ('auth_api', '0005_alter_student_name_alter_student_registernumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturehallattadence',
            name='name',
        ),
        migrations.AddField(
            model_name='lecturehallattadence',
            name='name',
            field=models.ManyToManyField(null=True, to='auth_api.student'),
        ),
    ]
