# Generated by Django 5.0 on 2023-12-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0018_remove_lecturehallattadence_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturehallattadence',
            options={'ordering': ['date']},
        ),
    ]
