# Generated by Django 5.0 on 2023-12-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0020_lecturehallattadence_mainname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturehallattadence',
            options={'ordering': ['date', 'mainName']},
        ),
        migrations.RenameField(
            model_name='lecturehallattadence',
            old_name='user',
            new_name='Class',
        ),
    ]
