# Generated by Django 5.0 on 2023-12-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0022_rename_periods_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='name',
        ),
        migrations.AddField(
            model_name='timetable',
            name='Class',
            field=models.ManyToManyField(to='attendanceManager.lecturehall'),
        ),
    ]
