# Generated by Django 5.0 on 2023-12-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0023_remove_timetable_name_timetable_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='periods',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
