# Generated by Django 5.0 on 2023-12-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0024_timetable_periods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='Class',
        ),
    ]
