# Generated by Django 5.0 on 2023-12-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0025_remove_timetable_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='Class',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendanceManager.lecturehall'),
        ),
    ]
