# Generated by Django 5.0 on 2023-12-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0027_rename_periods_timetable_friday_timetable_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='Class',
        ),
        migrations.AddField(
            model_name='timetable',
            name='Class',
            field=models.ManyToManyField(null=True, to='attendanceManager.lecturehall'),
        ),
    ]
