# Generated by Django 5.0 on 2023-12-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0030_alter_timetable_options_alter_timetable_class'),
        ('auth_api', '0006_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30, null=True)),
                ('hour', models.CharField(max_length=30, null=True)),
                ('period', models.CharField(max_length=255, null=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('Class', models.ManyToManyField(to='attendanceManager.lecturehall')),
                ('staffName', models.ManyToManyField(to='auth_api.staff')),
            ],
            options={
                'ordering': ['day', 'hour'],
            },
        ),
    ]
