# Generated by Django 5.0 on 2023-12-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0031_stafftimetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafftimetable',
            old_name='period',
            new_name='course',
        ),
    ]
