# Generated by Django 5.0 on 2024-02-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0032_rename_period_stafftimetable_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='classname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
