# Generated by Django 5.0 on 2024-02-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManager', '0033_timetable_classname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['classname', 'day', 'hour']},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
