# Generated by Django 5.0 on 2024-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendanceManager', '0034_alter_timetable_options_alter_timetable_classname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(blank=True, max_length=255)),
                ('subjectCode', models.CharField(blank=True, max_length=255)),
                ('subjectType', models.CharField(blank=True, max_length=255)),
                ('_lh', models.ManyToManyField(to='attendanceManager.lecturehall')),
            ],
            options={
                'ordering': ['subjectName'],
            },
        ),
    ]
